import java.util.*;

class Solution {
    public List<String> removeInvalidParentheses(String s) {
            int leftToRemove = 0;
                    int rightToRemove = 0;

                            // Step 1: Count minimum invalid '(' and ')' to remove
                                    for (char c : s.toCharArray()) {
                                                if (c == '(') {
                                                                leftToRemove++;
                                                                            } else if (c == ')') {
                                                                                            if (leftToRemove > 0) {
                                                                                                                leftToRemove--; // Valid pair matched
                                                                                                                                } else {
                                                                                                                                                    rightToRemove++; // Extra ')'
                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                                        }

                                                                                                                                                                                                Set<String> resultSet = new HashSet<>();
                                                                                                                                                                                                        backtrack(s, 0, 0, 0, leftToRemove, rightToRemove, new StringBuilder(), resultSet);
                                                                                                                                                                                                                return new ArrayList<>(resultSet);
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        private void backtrack(String s, int index, int openCount, int closeCount,
                                                                                                                                                                                                                                                   int leftToRemove, int rightToRemove,
                                                                                                                                                                                                                                                                              StringBuilder current, Set<String> result) {
                                                                                                                                                                                                                                                                                      // Base Case: Processed entire string
                                                                                                                                                                                                                                                                                              if (index == s.length()) {
                                                                                                                                                                                                                                                                                                          if (leftToRemove == 0 && rightToRemove == 0) {
                                                                                                                                                                                                                                                                                                                          result.add(current.toString());
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                  char c = s.charAt(index);
                                                                                                                                                                                                                                                                                                                                                                          int len = current.length();

                                                                                                                                                                                                                                                                                                                                                                                  // Option 1: Remove the character (if it's an extra '(' or ')')
                                                                                                                                                                                                                                                                                                                                                                                          if (c == '(' && leftToRemove > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                      backtrack(s, index + 1, openCount, closeCount, leftToRemove - 1, rightToRemove, current, result);
                                                                                                                                                                                                                                                                                                                                                                                                              } else if (c == ')' && rightToRemove > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                          backtrack(s, index + 1, openCount, closeCount, leftToRemove, rightToRemove - 1, current, result);
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                          // Option 2: Keep the character
                                                                                                                                                                                                                                                                                                                                                                                                                                                  current.append(c);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (c != '(' && c != ')') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Non-parenthesis characters are always included
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backtrack(s, index + 1, openCount, closeCount, leftToRemove, rightToRemove, current, result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else if (c == '(') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backtrack(s, index + 1, openCount + 1, closeCount, leftToRemove, rightToRemove, current, result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else if (c == ')' && openCount > closeCount) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Only keep ')' if there is a matching unmatched '(' before it
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backtrack(s, index + 1, openCount, closeCount + 1, leftToRemove, rightToRemove, current, result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      current.setLength(len); // Backtrack step
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }